### ISSUE TITLE
[Info] transport/internet/websocket: failed to validate host, request:mydomain

### ISSUE THREAD

**Issue by aliafshany** [XMPlusDev/XMPlusv1#5]
Hello there,
I have updated the panel to the latest version and also tried uninstalling the backend and installing the latest configuration with the new values.

Unfortunately, the panel won't get the certificates when it is set to HTTP, and you should set it to DNS.

There is a new problem as well. The panel tries to validate the host but it can't! I constantly receive this error in logs:

`Jul 13 21:16:48 ** XMPlus[***]: 2024/07/13 21:16:48 [Info] transport/internet/websocket: failed to validate host, request:mydomain, config:mydomain`

Also consider that the backend tries to validate an old host, not the new one.

**Comment by xcode75** [comment]
> Hello there,
> I have updated the panel to the latest version and also tried uninstalling the backend and installing the latest configuration with the new values.
> 
> Unfortunately, the panel won't get the certificates when it is set to HTTP, and you should set it to DNS.
> 
> There is a new problem as well. The panel tries to validate the host but it can't! I constantly receive this error in logs:
> 
> 
> `Jul 13 21:16:48 ** XMPlus[***]: 2024/07/13 21:16:48 [Info] transport/internet/websocket: failed to validate host, request:mydomain, config:mydomain`
> 
> Also consider that the backend tries to validate an old host, not the new one.

what do you mean? did you follow instructions and set a valid resolvable domain cos there is no issue with backend. Tested all protocol myself before posting update.
